### ISSUE TITLE
Нахождение мусорных флоатов

### ISSUE THREAD

**Issue by Prevter** [Prevter/FloatTool#2]
Иногда находит комбинации который при крафте выдают кривые флоаты.

Если крафтить 0.250000000 то может выйти либо 0.250000030 либо 0.249999985
Необходимо изучить этот момент подробнее

**Comment by Nemeshio** [comment]
Half fixed. Still have some issues

**Comment by Prevter** [comment]
Добавил IEEE754, но всё ещё может находить
